version: '3.4'

services:
  postgres:
    image: library/postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    networks:
      - my_network

  src:
    image: ${DOCKER_REGISTRY-}src
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my_network


networks:
  my_network:
