name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # TODO build, test and deploy project

      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install dependencies
        run: dotnet add src package Npgsql --version 9.0.2

      - name: Build
        run: dotnet build src --configuration Release

      - name: Publish
        run: dotnet publish src --configuration Release --output ./output

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
        run: |
          echo "Deploying to server..."
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

          docker build -t myapp:latest ./output

          ssh -o StrictHostKeyChecking=no -i private_key $USERNAME@$HOST << 'EOF'
          
            if ! command -v docker &> /dev/null
            then
                echo "Docker не установлен. Установите Docker перед продолжением."
                exit 1
            fi
            
            if [ "$(docker ps -q -f name=myapp)" ]; then
              docker stop myapp
              docker rm myapp
            fi
            
            docker run -d --name myapp -p 80:80 myapp:latest
            echo "Deploying Finished"
          EOF

          

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - name: Autograding
        uses: education/autograding@v1
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 1
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"
